#postgres connection
server:
  port: 8686
spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/eazyBank
      username: postgres
      password: system
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-management-port: true
    show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui



